#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

NODE22_BIN="${NODE22_BIN:-$HOME/.nvm/versions/node/v22.22.3/bin}"
export PATH="$NODE22_BIN:$PATH"

BASE_BRANCH="${BASE_BRANCH:-main}"
BRANCH_PREFIX="${BRANCH_PREFIX:-pi/improve-portfolio}"
BRANCH_NAME="${BRANCH_NAME:-${BRANCH_PREFIX}-$(date +%Y%m%d-%H%M%S)}"
CREATE_PR="${CREATE_PR:-0}"
PUSH_BRANCH="${PUSH_BRANCH:-$CREATE_PR}"
RUN_INSTALL="${RUN_INSTALL:-1}"
ALLOW_FAILED_VALIDATION="${ALLOW_FAILED_VALIDATION:-0}"
PI_MODEL="${PI_MODEL:-ollama/qwen3.6-35b-64k:latest}"
PI_THINKING="${PI_THINKING:-off}"
PROMPT_FILE="${PROMPT_FILE:-.rpiv/harness/portfolio-improvement-prompt.md}"
OBJECTIVE="${OBJECTIVE:-Improve the portfolio codebase with small, safe, reviewable changes. Prioritize build health, accessibility, responsive behavior, React/Three.js maintainability, and static export safety.}"

log() {
  printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*"
}

fail() {
  printf '\nerror: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

run_validation() {
  local failed=0

  log "Running TypeScript check"
  npx tsc --noEmit || failed=1

  log "Running lint"
  npm run lint || failed=1

  log "Running production build"
  npm run build || failed=1

  if [[ "$failed" -ne 0 ]]; then
    if [[ "$ALLOW_FAILED_VALIDATION" == "1" ]]; then
      log "Validation failed, but ALLOW_FAILED_VALIDATION=1 so the harness will continue"
      return 0
    fi
    fail "validation failed; fix the errors, then rerun or set ALLOW_FAILED_VALIDATION=1 for an exploratory branch"
  fi
}

require_command git
require_command npm
require_command npx
require_command pi

[[ -x "$NODE22_BIN/node" ]] || fail "Node 22.22.3 was not found at $NODE22_BIN/node"
[[ -f "$PROMPT_FILE" ]] || fail "prompt file not found: $PROMPT_FILE"

if [[ -n "$(git status --porcelain)" ]]; then
  fail "working tree is dirty; commit or stash changes before running the harness"
fi

git rev-parse --verify "$BASE_BRANCH" >/dev/null 2>&1 || fail "base branch not found locally: $BASE_BRANCH"

log "Creating branch $BRANCH_NAME from $BASE_BRANCH"
git switch "$BASE_BRANCH"
git switch -c "$BRANCH_NAME"

if [[ "$RUN_INSTALL" == "1" ]]; then
  log "Installing dependencies with npm ci"
  npm ci
fi

log "Starting Pi improvement pass with $PI_MODEL"
PI_PROMPT="$(cat "$PROMPT_FILE")

Objective:
$OBJECTIVE

Repository:
- Next.js 15 static export portfolio
- React 19
- React Three Fiber / Three.js scene
- GitHub Pages deployment from the repository remote

Hard constraints:
- Keep the change small enough for one reviewable PR.
- Do not add new runtime dependencies unless there is no simpler fix.
- Preserve existing portfolio behavior and visual intent.
- Do not create commits, branches, tags, or PRs. The harness script owns git operations.
- Run local validation before you finish, or clearly document why a validation command cannot pass.
"

pi \
  --approve \
  --no-session \
  --model "$PI_MODEL" \
  --thinking "$PI_THINKING" \
  --tools read,bash,edit,write,grep,find,ls \
  -p "$PI_PROMPT"

if [[ -z "$(git status --porcelain)" ]]; then
  log "Pi completed without file changes"
  git switch "$BASE_BRANCH"
  git branch -D "$BRANCH_NAME"
  exit 0
fi

run_validation

log "Committing changes"
git add -A
git commit -m "Improve portfolio health with local Pi automation

The local Pi harness inspected the portfolio, made a bounded codebase improvement, and passed the configured validation commands before committing.

Constraint: Uses local Ollama-backed Pi models, so the automation runs on this machine rather than GitHub Actions
Confidence: medium
Scope-risk: narrow
Reversibility: clean
Directive: Keep Pi-generated branches small; split broad redesigns into separate PRs
Tested: npx tsc --noEmit
Tested: npm run lint
Tested: npm run build
Not-tested: Manual browser and visual QA"

if [[ "$PUSH_BRANCH" == "1" || "$CREATE_PR" == "1" ]]; then
  require_command gh
  log "Checking GitHub authentication"
  gh auth status >/dev/null

  log "Pushing $BRANCH_NAME"
  git push -u origin "$BRANCH_NAME"
fi

if [[ "$CREATE_PR" == "1" ]]; then
  PR_BODY_FILE="$(mktemp)"
  {
    printf '## Summary\n'
    printf -- '- Local Pi harness made a bounded portfolio improvement pass.\n'
    printf -- '- Validation passed before commit.\n\n'
    printf '## Validation\n'
    printf -- '- `npx tsc --noEmit`\n'
    printf -- '- `npm run lint`\n'
    printf -- '- `npm run build`\n\n'
    printf '## Notes\n'
    printf 'Generated by `scripts/pi-pr-harness.sh` using `%s`.\n' "$PI_MODEL"
  } > "$PR_BODY_FILE"

  log "Creating pull request"
  gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH_NAME" \
    --title "Improve portfolio codebase with Pi" \
    --body-file "$PR_BODY_FILE"
else
  log "Branch is ready locally: $BRANCH_NAME"
  printf '\nTo push and open a PR later:\n'
  printf '  git push -u origin %s\n' "$BRANCH_NAME"
  printf '  gh pr create --base %s --head %s --fill\n' "$BASE_BRANCH" "$BRANCH_NAME"
fi
